name: Sample Orca Container Image Scan Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-cli:
    name: build-cli
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: demo-image
      PROJECT_KEY: slrk  
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Image Build
      run: |
        export GITHUB_SHA_SHORT="${GITHUB_SHA:0:8}"
        echo "Check GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" 
        echo "GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" >> $GITHUB_ENV
         
        docker build -t $IMAGE_NAME:${GITHUB_SHA_SHORT} .
        echo "Images list..."
        docker image ls

    - name: Set environment
      run: |
        cat <<EOF> "$GITHUB_ENV"
        ORCA_SECURITY_CONTAINER_DAEMON_HOST="unix:///var/run/docker.sock"
        ORCA_SECURITY_CONTAINER_DAEMON_HOST="tcp://0.0.0.0:2376"
        EOF

    - name: Run Orca Container Image Scan
      uses: orcasecurity/shiftleft-container-image-action@v1
      with:
        api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        project_key: slrk
        image: demo-image:${{ env.GITHUB_SHA_SHORT }}
        debug: true
        output:
          "results/"

    - name: Orca CLI - Security Scanning
      env:
        ORCA_SECURITY_API_TOKEN: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      run: |
        set +e
        apt update && apt install -y curl
        curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
        orca-cli -p "${PROJECT_KEY}" image scan ${IMAGE_NAME}:${GITHUB_SHA_SHORT}
